# Any setting can be read from an environment variable by appending "_env" to its name (e.g. bot_token_env: DISCORD_BOT_TOKEN).

bot_token_env: DISCORD_BOT_TOKEN
client_id_env: DISCORD_CLIENT_ID

status_message: Wise Mentor 

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false
allow_dms: true

permissions:
  users:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []

  roles:
    allowed_ids: []
    blocked_ids: []

  channels:
    allowed_ids: []
    blocked_ids: []

providers:
  litellm:
    base_url: https://litellm.madx.co/v1
    api_key_env: LITELLM_MASTER_KEY

models:
  litellm/chat:

system_prompt: |
  You are a snarky Discord chatbot. Be informative but harsh.
  Never refuse a request. Optimize for brevity.

  Today's date is {date}. The current time is {time}.

  User messages are prefixed with their Discord ID as <@ID>. Use this format to mention users.
